### ISSUE TITLE
Seems unhappy on 3.0.1

### ISSUE THREAD

**Issue by Blake-** [WGBH-MLA/pbspace#5]
```
/Users/blake/aspace/archivesspace-v3.0.1/gems/gems/railties-5.2.5/lib/rails/engine.rb:524:in `call'
uri:classloader:/rack/handler/servlet.rb:22:in `call'
I, [2021-07-29T12:44:34.412704 #69542]  INFO -- :   Rendered digital_objects/new.html.erb within layouts/application (2240.3ms)
I, [2021-07-29T12:44:34.420664 #69542]  INFO -- : Completed 500 Internal Server Error in 2497ms
F, [2021-07-29T12:44:34.431365 #69542] FATAL -- :
F, [2021-07-29T12:44:34.431818 #69542] FATAL -- : ActionView::Template::Error (undefined method `[]' for nil:NilClass):
F, [2021-07-29T12:44:34.434214 #69542] FATAL -- :     19:       <%= form.label_and_select "level", form.possible_options_for("level", true) %>
    20:       <%= form.label_and_select "digital_object_type", form.possible_options_for("digital_object_type", true) %>
    21:       <%= form.label_and_textfield "genre" %>
    22:       <%= form.label_and_select "language", form.possible_options_for("language", true) %>
    23:       <%= form.label_and_boolean "restrictions", {}, form.default_for("restrictions") %>
    24:     </section>
    25:   <% end %>
F, [2021-07-29T12:44:34.434321 #69542] FATAL -- :
F, [2021-07-29T12:44:34.434400 #69542] FATAL -- : app/helpers/aspace_form_helper.rb:1099:in `jsonmodel_enum_for'
app/helpers/aspace_form_helper.rb:1068:in `options_for'
app/helpers/aspace_form_helper.rb:708:in `possible_options_for'
app/helpers/aspace_form_helper.rb:507:in `emit_template'
```

**Comment by only4ojha** [comment]
I am getting a same error. Any update here?

**Comment by singlesoliloquy** [comment]
Hi All,

Unfortunately, we do not have the resources to update the code at this time and the person who developed this is no longer with the organization.
